import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../public/globals.css";
import clsx from "clsx";
import { Header } from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "bg-muted/40")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
